/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ConfigIndexRouteImport } from './routes/config/index'
import { Route as ConnectionsIndexRouteImport } from './routes/connections/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as EventsIndexRouteImport } from './routes/events/index'
import { Route as EventsIdRouteImport } from './routes/events/$id'
import { Route as LogsIndexRouteImport } from './routes/logs/index'
import { Route as MappingIndexRouteImport } from './routes/mapping/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/config/',
  path: '/config/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnectionsIndexRoute = ConnectionsIndexRouteImport.update({
  id: '/connections/',
  path: '/connections/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIndexRoute = EventsIndexRouteImport.update({
  id: '/events/',
  path: '/events/',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsIdRoute = EventsIdRouteImport.update({
  id: '/events/$id',
  path: '/events/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LogsIndexRoute = LogsIndexRouteImport.update({
  id: '/logs/',
  path: '/logs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingIndexRoute = MappingIndexRouteImport.update({
  id: '/mapping/',
  path: '/mapping/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/config/': typeof ConfigIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/mapping/': typeof MappingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/config': typeof ConfigIndexRoute
  '/connections': typeof ConnectionsIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/events': typeof EventsIndexRoute
  '/logs': typeof LogsIndexRoute
  '/mapping': typeof MappingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/events/$id': typeof EventsIdRoute
  '/config/': typeof ConfigIndexRoute
  '/connections/': typeof ConnectionsIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/events/': typeof EventsIndexRoute
  '/logs/': typeof LogsIndexRoute
  '/mapping/': typeof MappingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/events/$id'
    | '/config/'
    | '/connections/'
    | '/dashboard/'
    | '/events/'
    | '/logs/'
    | '/mapping/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/events/$id'
    | '/config'
    | '/connections'
    | '/dashboard'
    | '/events'
    | '/logs'
    | '/mapping'
  id:
    | '__root__'
    | '/'
    | '/events/$id'
    | '/config/'
    | '/connections/'
    | '/dashboard/'
    | '/events/'
    | '/logs/'
    | '/mapping/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EventsIdRoute: typeof EventsIdRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
  ConnectionsIndexRoute: typeof ConnectionsIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  EventsIndexRoute: typeof EventsIndexRoute
  LogsIndexRoute: typeof LogsIndexRoute
  MappingIndexRoute: typeof MappingIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config/': {
      id: '/config/'
      path: '/config'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connections/': {
      id: '/connections/'
      path: '/connections'
      fullPath: '/connections/'
      preLoaderRoute: typeof ConnectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/': {
      id: '/events/'
      path: '/events'
      fullPath: '/events/'
      preLoaderRoute: typeof EventsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events/$id': {
      id: '/events/$id'
      path: '/events/$id'
      fullPath: '/events/$id'
      preLoaderRoute: typeof EventsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logs/': {
      id: '/logs/'
      path: '/logs'
      fullPath: '/logs/'
      preLoaderRoute: typeof LogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping/': {
      id: '/mapping/'
      path: '/mapping'
      fullPath: '/mapping/'
      preLoaderRoute: typeof MappingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EventsIdRoute: EventsIdRoute,
  ConfigIndexRoute: ConfigIndexRoute,
  ConnectionsIndexRoute: ConnectionsIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  EventsIndexRoute: EventsIndexRoute,
  LogsIndexRoute: LogsIndexRoute,
  MappingIndexRoute: MappingIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
