spring.application.name=price_sync

spring.datasource.url=jdbc:postgresql://localhost:5432/price_sync
spring.datasource.username=macbookpro
spring.datasource.password=
app.security.api-key=hq-secret-key-123
app.security.ip-allowlist=127.0.0.1,0:0:0:0:0:0:0:1
app.security.hmac-secret=shared-secret-abc
app.security.timestamp-window-seconds=300
server.error.include-stacktrace=never
